### ISSUE TITLE
Command using in Lisp have in python?

### ISSUE THREAD

**Issue by filipesantana18** [jakdot/pyactr#2]
In ACT-R Lisp, I can do this kind of command
`!eval! (< =variable 2)`

It is possible that this type of execution is done aquino pyactr?
Example:

playing_memory.productionstring(name="startplaying", string="""
  =goal>
    isa  playgame
    game =game
    activity None
  !eval! ( =game == "memory")
==>
=goal>
isa playgame
activity presskey""")`

`

**Comment by jakdot** [comment]
A short answer is that there is no eval command in pyactr. However, you can fully emulate this kind of behavior and you can do so by interspersing python code with execution of pyactr. This also should make it clearer that you are (potentially) leaving the realm of ACT-R, which I think the eval command in Lisp obfuscates.

The disadvantage is that emulating the behavior of eval is a bit roundabout and more cumbersome. For example, one way to do it is to create a dedicated buffer that stores values that have to be evaluated to True in order for some conditions to run.
I am giving an example below. This is the counting model (count from 2 to 4), but this time, the model stops counting when it reaches 4 because the eval buffer is evaluated to True (see the rule stop). Crucially, the value of the eval buffer is set outside of ACT-R and directly in Python. This is done in the last bit of the code (see the while loop, starting with while True). Basically, we run the simulation and at every step we can check any value in an if-clause. (In this case, we check that the retrieval buffer has the value 4 in the slot 'first'). If this is so, we set the eval buffer to True and the rule stop can fire.

```
import pyactr as actr
from simpy.core import EmptySchedule

counting = actr.ACTRModel()

#Each chunk type should be defined first.
actr.chunktype("countOrder", ("first", "second"))
actr.chunktype("Eval", ("value"))
#Chunk type is defined as (name, attributes)

#Attributes are written as an iterable (above) or as a string, separated by comma:
actr.chunktype("countOrder", "first, second")

dm = counting.decmem
#this creates declarative memory

x = actr.chunkstring(string="\
    isa countOrder\
    first 1\
    second 2")

dm.add(x)
dm.add(actr.chunkstring(string="\
    isa countOrder\
    first 2\
    second 3"))
y = actr.chunkstring(string="\
    isa countOrder\
    first 3\
    second 4")
dm.add(y)
dm.add(actr.chunkstring(string="\
    isa countOrder\
    first 4\
    second 5"))

actr.chunktype("countFrom", ("start", "end", "count"))

#production rules follow; using productionstring, they are similar to Lisp ACT-R

counting.productionstring(name="start", string="""
    =g>
    isa countFrom
    start =x
    count None
    ==>
    =g>
    isa countFrom
    count =x
    +retrieval>
    isa countOrder
    first =x""")

counting.productionstring(name="increment", string="""
    =g>
    isa     countFrom
    count       =x
    end         ~=x
    =retrieval>
    isa     countOrder
    first       =x
    second      =y
    ==>
    =g>
    isa     countFrom
    count       =y
    +retrieval>
    isa     countOrder
    first       =y""")

counting.productionstring(name="stop", string="""
    ?g>
    buffer  full
    =eval>
    isa     Eval
    value   True
    ==>
    =eval>
    isa     Eval
    value   None
    ~g>""")

#adding stuff to goal buffer
counting.goal.add(actr.chunkstring(string="isa countFrom start 2 end 4"))

#creating fake buffer to mimic !eval!
counting.set_goal("eval")
counting.goals["eval"].add(actr.chunkstring(string="isa Eval value None"))


x = counting.simulation()

#run the simulation
while True:
        try:
            # do one step in simulation
            x.step()
        except EmptySchedule:
            # unless there are no steps, in which case - break
            break
        # now we add some arbitrary condition which is like !eval! - in this
        # case we test whether the chunk that is in the retrieval buffer has the
        # value 4 in the slot first
        if counting.retrieval and actr.chunkstring(string="isa countOrder first 4") < counting.retrieval.copy().pop():
            # if the condition is valid we will set the value in the buffer eval
            # to True; if it set to True, the rule 'stop' can fire
            counting.goals["eval"].add(actr.chunkstring(string="isa Eval value True"))
```
