### ISSUE TITLE
Buffer/state check in "semantic" tutorial

### ISSUE THREAD

**Issue by asmaloney** [jakdot/pyactr#20]
The _semantic.lisp_ tutorial from the main ACT-R code has the following production:

```lisp
(P fail
   =goal>
      ISA         is-member
      object      =obj1
      category    =cat  
      judgment    pending
    
   ?retrieval>
      buffer      failure
==>
   =goal>
      judgment    no
)
```

Note that it is checking if the `retrieval` buffer state is `failure`.

This has been translated to pyactr's tutorial as:

```python
semantic.productionstring(name="fail", string="""
        =g>
        isa     isMember
        object  =obj1
        category    =cat
        judgment    'pending'
        ?retrieval>
        state   error
        ==>
        =g>
        isa     isMember
        judgment 'no'""")
```

This is checking if the _declarative memory module_ state is `error` (buffer checks are on the buffer, state checks are on the module). 

Is this necessarily equivalent? Was it done this way because pyactr doesn't support `failure` state on buffers?

(Context: https://github.com/asmaloney/gactar/discussions/221 )

**Comment by jakdot** [comment]
Internally, pyactr actually checks the error status on the retrieval buffer, not on the declarative memory module.

Regarding the productionstring you show - it is true that error is specified as a value of the keyword "state". But that is just a convention here - I used another keyword next to "buffer" because queries about the content of a buffer (empty/full) and the state of a buffer process (failure, busy) might be combined in one rule, and productionstring in pyactr does not allow two values to be assigned to one key.

Is there another reason why you thought the check of error is done on the declarative memory module?

**Comment by asmaloney** [comment]
Thank you for the response.

> Is there another reason why you thought the check of error is done on the declarative memory module?

Yes - from the ACT-R manual pp. 229-230:

>A query is one or more tests of a buffer and/or its owning module. There are several default queries which may be made for every buffer and a module may provide many more queries to which it will respond. Each query will produce either a true or false result. The production will only match if the result of each query is true, or if the result is false and the negative test modifier, ‘-’, is used. The queries that can be specified for every buffer are:

* buffer empty
* buffer full
* buffer failure
* buffer requested
* buffer unrequested
* state free
* state busy
* state error
* error t
* error nil
 
> The first five are tests of the buffer itself and the module is not involved in that process. The rest, and any others which a module provides, are tests which are relayed to the module to get its response.

**Comment by asmaloney** [comment]
Closing this issue in favour of #21 which covers this more generally.
